# Generated by Django 2.2.5 on 2019-11-02 04:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('matchThumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/')),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('numParticipants', models.PositiveSmallIntegerField(default=1)),
                ('isFull', models.BooleanField(default=False)),
                ('locationText', models.CharField(default='', max_length=100)),
                ('period', models.PositiveSmallIntegerField(default=0)),
                ('additionalInfo', models.TextField(default='')),
                ('isAgeRestricted', models.BooleanField(default=False)),
                ('restrictAgeFrom', models.PositiveSmallIntegerField(default=0)),
                ('restrictAgeTo', models.PositiveSmallIntegerField(default=0)),
                ('isGenderRestricted', models.BooleanField(default=False)),
                ('restrictedGender', models.BooleanField(default=False)),
                ('timeBegin', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeEnd', models.DateTimeField(default=django.utils.timezone.now)),
                ('viewCount', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaker.Category')),
            ],
        ),
    ]
