# Generated by Django 2.2.5 on 2019-11-02 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matchmaker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hostUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
