# Generated by Django 2.2.5 on 2019-11-05 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=None)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_match', to='matchmaker.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
