# Generated by Django 2.2.5 on 2019-11-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_thumbnail',
            field=models.ImageField(blank=True, default='thumbnail/default-user.png', null=True, upload_to='thumbnail/'),
        ),
    ]
