# Generated by Django 2.2.5 on 2019-11-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='additionalInfo',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='categoryID',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='hostUserID',
            new_name='host_user_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='isAgeRestricted',
            new_name='is_age_restricted',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='isFull',
            new_name='is_full',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='isGenderRestricted',
            new_name='is_gender_restricted',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='locationText',
            new_name='location_text',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='matchThumbnail',
            new_name='match_thumbnail',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='numParticipants',
            new_name='num_participants',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='restrictAgeFrom',
            new_name='restrict_age_from',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='restrictAgeTo',
            new_name='restrict_age_to',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='restrictedGender',
            new_name='restricted_gender',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='timeBegin',
            new_name='time_begin',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='timeEnd',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='viewCount',
            new_name='view_count',
        ),
    ]
