# Generated by Django 2.2.5 on 2019-10-27 06:36

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='additionalInfo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='match',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='match',
            name='categoryID',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Game'), (2, 'Study'), (3, 'Sports')], default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='isAgeRestricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='isFull',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='isGenderRestricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='locationText',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='numParticipants',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='period',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='restrictAgeFrom',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='restrictAgeTo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='restrictedGender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='timeBegin',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 6, 36, 3, 889128, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='match',
            name='timeEnd',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 6, 36, 3, 889219, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='match',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='viewCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
