# Generated by Django 2.2.5 on 2019-11-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_match_hostuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='hostUser',
            new_name='hostUserID',
        ),
    ]
