# Generated by Django 2.2.5 on 2019-10-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_auto_20191027_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='timeBegin',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='timeEnd',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
