# Generated by Django 2.2.5 on 2019-11-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0002_remove_match_num_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
