# Generated by Django 2.2.5 on 2019-11-02 14:36

from django.db import migrations
import django.utils.timezone
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0004_auto_20191102_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_on',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='time_begin',
            field=unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='match',
            name='time_end',
            field=unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now),
        ),
    ]
