# Generated by Django 2.2.5 on 2019-11-02 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0007_auto_20191102_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time_begin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='match',
            name='time_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
