# Generated by Django 2.2.5 on 2019-11-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0008_auto_20191102_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='host_user_id',
            new_name='host_user',
        ),
    ]
